### ISSUE TITLE
Missing angles in ITP files

### ISSUE THREAD

**Issue by aristogato-gm** [HMakkiMD/PolySMart#1]
Hello,

I've executed the test case and noticed that the final "itp" files are missing the new angles specified in "new_angles_parameters.txt." This inconsistency is unexpected as the "itp" files in the output directory do contain information about at least one of those angles. Could you help me with this issue, please? Thank you! Great work with PolySmart!

**Comment by mmousavifard** [comment]
Hello,
The "new_angles_parameters.txt." is now based on bead names (instead of bead types) and we had forgotten to edit this input file in the test case. It is modified now and you can use it for input again. Thank you for your notice and I hope it helps you.

**Comment by aristogato-gm** [comment]
Thank you very much for your response. I've executed the test case, and now the generated "itp" files do contain the new angles. I've also run a system of interest in my research, and everything seems fine with the files.
